### ISSUE TITLE
Exclude WHATWG Review Drafts

### ISSUE THREAD

**Issue by foolip** [foolip/bikeshed-tests#10]
Files like github/whatwg/xhr/review-drafts/2018-08.bs are included. We will accumulate more and more of these, and we won't have the ability to update them.

@annevk @domenic am I correct to think that we'll never try to build these from source after publication, so that it doesn't matter if Bikeshed breaks when trying to build old drafts?

**Comment by foolip** [comment]
@tabatkins

**Comment by annevk** [comment]
Took me a while, but generally yes, see https://github.com/whatwg/whatwg.org/issues/197#issuecomment-385225422.
